spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp_main
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    reactor:
      netty: DEBUG

security:
  basic:
    enabled: false

management:
  security:
    enabled: false